steps:
  # Шаг сборки образа Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/[PROJECT_ID]/clearjson', '.']
    
  # Шаг загрузки образа Docker в Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/[PROJECT_ID]/clearjson']
    
  # Шаг применения Kubernetes-манифеста для развертывания
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment.yaml']
