apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearjson-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clearjson
  template:
    metadata:
      labels:
        app: clearjson
    spec:
      containers:
        - name: clearjson
          image: clearjson
          command: ["python", "ClearJSON.py"]
